### ISSUE TITLE
 There is no main category related to context: x - how to create a parentless category?

### ISSUE THREAD

**Issue by clytemnestra** [sonata-project/SonataMediaBundle#862]
Greetings, I am trying to attach media to my User(FOSUser) class, more exactly add a profile picture for each user through a Symfony Command. The error that I am getting is

```php
 There is no main category related to context: profile_pics  
```

And the way to solve it is to manually go into the database and create a category with no parent. Is there no way to create such a category through the Sonata Admin?

Here is what I'm using etc.:

my code
```php
            $media = new Media();
            $media->setBinaryContent(getcwd().'/web'.$image);
            $media->setContext('profile_pics');
            $media->setProviderName('sonata.media.provider.image');
            $this->getContainer()->get('sonata.media.manager.media')->save($media);
```

the configuration
```yml
sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        profile_pics:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
```

my composer
```composer
   "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "doctrine/doctrine-migrations-bundle": "^1.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "cunningsoft/chat-bundle": "^0.4.0",
        "knplabs/knp-time-bundle": "^1.3",
        "knplabs/knp-paginator-bundle": "^2.4",
        "knplabs/knp-menu-bundle": "~2",
        "twig/extensions": "^1.3",
        "sonata-project/core-bundle": "^2.3",
        "sonata-project/block-bundle": "^2.3.8",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "~2.4@dev",

        "sonata-project/datagrid-bundle": "~2.2@dev",
        "sonata-project/classification-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "^2.1",
        "sonata-project/intl-bundle": "^2.2",
        "sonata-project/media-bundle": "dev-master",
        "jms/serializer-bundle": "^1.0",
        "kriswallsmith/buzz": "^0.15.0"

    },
```

my user class part
```php
class User extends BaseUser implements AuthorInterface
    /**
     * @ORM\OneToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media",cascade={"persist"})
     * @ORM\JoinColumn(referencedColumnName="id",onDelete="CASCADE")
     */
    protected $profilepic;

```

**Comment by clytemnestra** [comment]
It seems that whenever I want to filter media in the Sonata admin panel it automatically created the context and category for the context. For instance, I have 3 contexts: default, images, private, and whenever I go to the Media list page which automatically filters the default context, that will create the context in the database automatically. Where does this happen exactly?

**Comment by OskarStark** [comment]
@core23 can we fix this with your command?

**Comment by core23** [comment]
@OskarStark Yes, the new command (https://github.com/sonata-project/SonataMediaBundle/pull/899) should fix this

**Comment by OskarStark** [comment]
but if you don't have these root categories and create some category with the UI, everything works fine.... oO

**Comment by lightglitch** [comment]
@OskarStark The command creates the context or categories mas I still get the error because of 
[this comparison](https://github.com/sonata-project/SonataMediaBundle/blob/master/Listener/ORM/MediaEventSubscriber.php#L86) because
```
$media->getContext() // is a string 
```
and the keys of `$this->rootCategories` are the table integer ids.
I'm using 
```
$this->getMediaManager()->save($media, $context, $provider);
```

**Comment by clytemnestra** [comment]
The categories are not automatically created from the contexts.
Do we have to run the command every time we add a new context?

**Comment by OskarStark** [comment]
@core23 van you help?

Am Freitag, 4. März 2016 schrieb George Irimiciuc :

**Comment by core23** [comment]
Yes, every time you create new contexts, you have to run the command @clytemnestra

**Comment by debach** [comment]
That means that we have to change our fixtures for functional tests as well. What makes it worse is that construction of categories appears to be quite elaborate – see FixMediaContextCommand.

I have the feeling that the ClassificationBundle dependency is *much* too intrusive. Shouldn’t it be optional? I don’t need the classification functionality, yet it makes the MediaBundle a lot more difficult to use: configuration, “easy-extends”, more configuration, change fixtures – just so I end up with a default category.

Are there plans to decouple the bundles?

**Comment by core23** [comment]
> I have the feeling that the ClassificationBundle dependency is much too intrusive. Shouldn’t it be optional? 

There is an open PR for that https://github.com/sonata-project/SonataMediaBundle/pull/794 @debach

**Comment by bipa9021** [comment]
@clytemnestra can you please tell me where I have to put this code?
            $media = new Media();
            $media->setBinaryContent(getcwd().'/web'.$image);
            $media->setContext('profile_pics');
            $media->setProviderName('sonata.media.provider.image');
            $this->getContainer()->get('sonata.media.manager.media')->save($media);

**Comment by core23** [comment]
Your question is not related to this issue, please use Stack Overflow for this @clytemnestra
