### ISSUE TITLE
FileLoaderLoadException after installing SonataMediaBundle

### ISSUE THREAD

**Issue by Zomorrouda** [sonata-project/SonataMediaBundle#912]
An error occurred after installing sonata media bundle (~2.4@dev ) : 

**[Symfony\Component\Config\Exception\FileLoaderLoadException]  
Cannot automatically determine base route name, please define a default `baseRouteName` value for the admin class `Sonata\MediaBundle\Admin\ORM\MediaAdmin` in /project/directory/app/config/. (which is being imported from "/project/directory/app/config/routing.yml").**

My routing.yml

``` yaml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
```

NB: I'm working with Symfony 2.7

**Comment by OskarStark** [comment]
could you please post the output of ``composer show -i`` ?

**Comment by nicolasricci** [comment]
@OskarStark I had the same problem yesterday with the following Sonata distribution. thanks for your help

> sonata-project/admin-bundle              dev-master 0e12021 Symfony SonataAdminBundle
> sonata-project/block-bundle              2.3.9              Symfony SonataBlockBundle
> sonata-project/cache                     1.0.7              Cache library
> sonata-project/classification-bundle     dev-master 8a2a1b5 Symfony SonataClassificationBundle
> sonata-project/core-bundle               2.3.10             Symfony SonataCoreBundle
> sonata-project/datagrid-bundle           dev-master 0749e71 Symfony SonataDatagridBundle
> sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
> sonata-project/doctrine-orm-admin-bundle dev-master e8eb83f Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
> sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle
> sonata-project/exporter                  1.4.1              Lightweight Exporter library
> sonata-project/intl-bundle               2.2.3              Symfony SonataIntlBundle
> sonata-project/media-bundle              dev-master f3a82e8 Symfony SonataMediaBundle
> sonata-project/notification-bundle       2.3.2              Symfony SonataNotificationBundle
>

**Comment by Zomorrouda** [comment]
i have fixed that problem by fixing the SnataMediaBundle version on 2.4.x-dev

**Comment by nicolasricci** [comment]
I had to revert to ^2.3 because I needed a more recent version for the aws-sdk-php but I still have the same issue. Could you tell me what are your other sonata bundles version please?

**Comment by Zomorrouda** [comment]
```json
    "sonata-project/admin-bundle": "2.4.x-dev",
    "sonata-project/doctrine-orm-admin-bundle": "~2.4@dev",
    "sonata-project/user-bundle": "~2.2@dev",
    "sonata-project/easy-extends-bundle": "dev-master",
    "sonata-project/datagrid-bundle": "2.2.x-dev",
    "sonata-project/classification-bundle": "2.3.x-dev",
    "sonata-project/intl-bundle": "~2.2@dev",
    "sonata-project/media-bundle": "2.4.x-dev",
    "sonata-project/translation-bundle": "1.0.1"
```

**Comment by taalayuulu** [comment]
I have updated my composer file. But it still remains throw previous error

**Comment by jordisala1991** [comment]
seems like an error on older versions
